apiVersion: "nais.io/v1alpha1"
kind: "Alert"
metadata:
  name: syfoalerts-sbs
  labels:
    team: teamsykefravr
spec:
  receivers:
    slack:
      channel: '#syfo-alerts-prod'
      #prependText: '<!here> | '
  alerts:
    - alert: syfo-sbs-app-nede
      expr: kube_deployment_status_replicas_available{deployment=~"sykefravaerarbeidsgiver"} == 0
      for: 2m
      description: "{{ $labels.deployment }} er nede"
      action: "Se `kubectl kubectl get pod  | grep {{ $labels.deployment }}` for å se podder, og `kubectl logs $podnavn` for logger"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfo-sbs-mangler-metrikker
      expr: absent(up{app=~"sykefravaerarbeidsgiver",job="kubernetes-pods"})
      for: 5m
      description: "{{ $labels.app }} rapporterer ingen metrikker i {{ $labels.kubernetes_namespace }}"
      action: "Sjekk om {{ $labels.app }} i {{ $labels.kubernetes_namespace }} er oppe"
      sla: respond within 1h, during office hours
      severity: danger
