apiVersion: "nais.io/v1alpha1"
kind: "Alert"
metadata:
  name: syfoalerts
  labels:
    team: teamsykefravr
spec:
  receivers:
    slack:
      channel: '#syfo-alerts-prod'
      #prependText: '<!here> | '
  alerts:
    - alert: syfo-app-nede
      expr: up{app=~"pdf-gen|syfoarbeidsgivertilgang|syfogsak|syfoinntektsmelding|syfonarmesteleder|syfoservicestrangler|syfosoknadvarsel|syfosoknad|syfosyketilfelle|syfoaltinn|syfovarsel",job="kubernetes-pods"} == 0
      for: 2m
      description: "{{ $labels.app }} er nede i {{ $labels.kubernetes_namespace }}"
      action: "Se `kubectl describe pod {{ $labels.kubernetes_pod_name }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }}` for logger"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfo-mangler-metrikker
      expr: absent(up{app=~"pdf-gen|syfoarbeidsgivertilgang|syfogsak|syfoinntektsmelding|syfonarmesteleder|syfoservicestrangler|syfosoknadvarsel|syfosoknad|syfosyketilfelle|syfoaltinn|syfovarsel",job="kubernetes-pods"})
      for: 3m
      description: "{{ $labels.app }} rapporterer ingen metrikker i {{ $labels.kubernetes_namespace }}"
      action: "Sjekk om {{ $labels.app }} i {{ $labels.kubernetes_namespace }} er oppe"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfosoknadvarsel-lytter-stoppet
      expr: sum(syfosoknadvarsel_kafkalytter_stoppet) > 0
      for: 3m
      description: "{{ $labels.app }} sin kafkalytter har stoppet i {{ $labels.kubernetes_namespace }}"
      action: "Kafkalytter stoppet på syfosoknadvarsel. Sjekk logger, og evt. `kubectl delete pod {{ $labels.kubernetes_pod_name }}` for å restarte"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfogsak-lytter-stoppet
      expr: sum(syfogsak_kafkalytter_stoppet) > 0
      for: 3m
      description: "{{ $labels.app }} sin kafkalytter har stoppet i {{ $labels.kubernetes_namespace }}"
      action: "Kafkalytter stoppet på syfogsak. Sjekk logger, og evt. `kubectl delete pod {{ $labels.kubernetes_pod_name }}` for å restarte"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfogsak-ingenSoknaderBehandlet
      expr: sum(increase(syfogsak_innsending_behandlet_total[24h])) < 0.8
      for: 1m
      description: "{{ $labels.app }} har ikke behandlet soknader på 24 timer i {{ $labels.kubernetes_namespace }}"
      action: "Syfogsak har ikke behandlet soknader på 24 timer. Sjekk i errorloggen: https://logs.adeo.no/goto/c117ef2a4003c420e43d391f8007ddda , og evt. `kubectl delete pod {{ $labels.kubernetes_pod_name }}` for å restarte"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfovarsel-lytter-stoppet
      expr: sum(syfovarsel_kafkalytter_stoppet) > 0
      for: 3m
      description: "{{ $labels.app }} sin kafkalytter har stoppet i {{ $labels.kubernetes_namespace }}"
      action: "Kafkalytter stoppet på syfovarsel. Sjekk logger, og evt. `kubectl delete pod {{ $labels.kubernetes_pod_name }}` for å restarte"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfoaltinn-lytter-stoppet
      expr: sum(syfoaltinn_kafkalytter_stoppet) > 0
      for: 3m
      description: "{{ $labels.app }} sin kafkalytter har stoppet i {{ $labels.kubernetes_namespace }}"
      action: "Kafkalytter stoppet på syfoaltinn. Sjekk logger, og evt. `kubectl delete pod {{ $labels.kubernetes_pod_name }}` for å restarte"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfosyketilfelle-lytter-stoppet
      expr: sum(syfosyketilfelle_kafkalytter_stoppet) > 0
      for: 3m
      description: "{{ $labels.app }} sin kafkalytter har stoppet i {{ $labels.kubernetes_namespace }}"
      action: "Kafkalytter stoppet på syfosyketilfelle. Sjekk logger, og evt. `kubectl delete pod {{ $labels.kubernetes_pod_name }}` for å restarte"
      sla: respond within 1h, during office hours
      severity: danger
