name: Deploy to dev and prod
on:
  push:
    branches:
      - master
jobs:
  deploy_prod:
    name: Deploy alert til prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Apply alert configuration file to prod-fss
        uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: prod-fss
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: syfoalerts.yaml
      - name: Apply alert configuration file to prod-sbs
        uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: prod-sbs
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: syfoalerts-sbs.yaml
  