name: Deploy to dev
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  deploy_prod:
    name: Deploy alert til dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Apply alert configuration file to dev-fss
        uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-fss
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: test/syfoalerts_test.yaml